# Copyright © 2019 Axel Svensson <mail@axelsvensson.com>
# This file is part of keyboa version <VERSION>
# License: See LICENSE

# https://www.unicode.org/charts/PDF/U2500.pdf

boxlist=[

# All of these characters are intended for compatibility with
# character cell graphic sets in use prior to 1990.

	#              ┌───── Left:  l=light, h=heavy, -=none
	#              │┌──── Down:  l=light, h=heavy, -=none
	#              ││┌─── Up:    l=light, h=heavy, -=none
	#              │││┌── Right: l=light, h=heavy, -=none
	#              ││││┌─ Dash:  2=double, 3=triple, 4=quadruple, N=none
	#              │││││┌ Arc:   Y=Yes, N=No
# Light and heavy solid lines
	(0x2500, "─", "l--lNN", "BOX DRAWINGS LIGHT HORIZONTAL"),
	(0x2501, "━", "h--hNN", "BOX DRAWINGS HEAVY HORIZONTAL"),
	(0x2502, "│", "-ll-NN", "BOX DRAWINGS LIGHT VERTICAL"),
	(0x2503, "┃", "-hh-NN", "BOX DRAWINGS HEAVY VERTICAL"),
# Light and heavy dashed lines
	(0x2504, "┄", "l--l3N", "BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL"),
	(0x2505, "┅", "h--h3N", "BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL"),
	(0x2506, "┆", "-ll-3N", "BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL"),
	(0x2507, "┇", "-hh-3N", "BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL"),
	(0x2508, "┈", "l--l4N", "BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL"),
	(0x2509, "┉", "h--h4N", "BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL"),
	(0x250A, "┊", "-ll-4N", "BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL"),
	(0x250B, "┋", "-hh-4N", "BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL"),
# Light and heavy line box components
	(0x250C, "┌", "-l-lNN", "BOX DRAWINGS LIGHT DOWN AND RIGHT"),
	(0x250D, "┍", "-l-hNN", "BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY"),
	(0x250E, "┎", "-h-lNN", "BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT"),
	(0x250F, "┏", "-h-hNN", "BOX DRAWINGS HEAVY DOWN AND RIGHT"),
	(0x2510, "┐", "ll--NN", "BOX DRAWINGS LIGHT DOWN AND LEFT"),
	(0x2511, "┑", "hl--NN", "BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY"),
	(0x2512, "┒", "lh--NN", "BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT"),
	(0x2513, "┓", "hh--NN", "BOX DRAWINGS HEAVY DOWN AND LEFT"),
	(0x2514, "└", "--llNN", "BOX DRAWINGS LIGHT UP AND RIGHT"),
	(0x2515, "┕", "--lhNN", "BOX DRAWINGS UP LIGHT AND RIGHT HEAVY"),
	(0x2516, "┖", "--hlNN", "BOX DRAWINGS UP HEAVY AND RIGHT LIGHT"),
	(0x2517, "┗", "--hhNN", "BOX DRAWINGS HEAVY UP AND RIGHT"),
	(0x2518, "┘", "l-l-NN", "BOX DRAWINGS LIGHT UP AND LEFT"),
	(0x2519, "┙", "h-l-NN", "BOX DRAWINGS UP LIGHT AND LEFT HEAVY"),
	(0x251A, "┚", "l-h-NN", "BOX DRAWINGS UP HEAVY AND LEFT LIGHT"),
	(0x251B, "┛", "h-h-NN", "BOX DRAWINGS HEAVY UP AND LEFT"),
	(0x251C, "├", "-lllNN", "BOX DRAWINGS LIGHT VERTICAL AND RIGHT"),
	(0x251D, "┝", "-llhNN", "BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY"),
	(0x251E, "┞", "-lhlNN", "BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT"),
	(0x251F, "┟", "-hllNN", "BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT"),
	(0x2520, "┠", "-hhlNN", "BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT"),
	(0x2521, "┡", "-lhhNN", "BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY"),
	(0x2522, "┢", "-hlhNN", "BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY"),
	(0x2523, "┣", "-hhhNN", "BOX DRAWINGS HEAVY VERTICAL AND RIGHT"),
	(0x2524, "┤", "lll-NN", "BOX DRAWINGS LIGHT VERTICAL AND LEFT"),
	(0x2525, "┥", "hll-NN", "BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY"),
	(0x2526, "┦", "llh-NN", "BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT"),
	(0x2527, "┧", "lhl-NN", "BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT"),
	(0x2528, "┨", "lhh-NN", "BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT"),
	(0x2529, "┩", "hlh-NN", "BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY"),
	(0x252A, "┪", "hhl-NN", "BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY"),
	(0x252B, "┫", "hhh-NN", "BOX DRAWINGS HEAVY VERTICAL AND LEFT"),
	(0x252C, "┬", "ll-lNN", "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL"),
	(0x252D, "┭", "hl-lNN", "BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT"),
	(0x252E, "┮", "ll-hNN", "BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT"),
	(0x252F, "┯", "hl-hNN", "BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY"),
	(0x2530, "┰", "lh-lNN", "BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT"),
	(0x2531, "┱", "hh-lNN", "BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY"),
	(0x2532, "┲", "lh-hNN", "BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY"),
	(0x2533, "┳", "hh-hNN", "BOX DRAWINGS HEAVY DOWN AND HORIZONTAL"),
	(0x2534, "┴", "l-llNN", "BOX DRAWINGS LIGHT UP AND HORIZONTAL"),
	(0x2535, "┵", "h-llNN", "BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT"),
	(0x2536, "┶", "l-lhNN", "BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT"),
	(0x2537, "┷", "h-lhNN", "BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY"),
	(0x2538, "┸", "l-hlNN", "BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT"),
	(0x2539, "┹", "h-hlNN", "BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY"),
	(0x253A, "┺", "l-hhNN", "BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY"),
	(0x253B, "┻", "h-hhNN", "BOX DRAWINGS HEAVY UP AND HORIZONTAL"),
	(0x253C, "┼", "llllNN", "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL"),
	(0x253D, "┽", "hlllNN", "BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT"),
	(0x253E, "┾", "lllhNN", "BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT"),
	(0x253F, "┿", "hllhNN", "BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY"),
	(0x2540, "╀", "llhlNN", "BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT"),
	(0x2541, "╁", "lhllNN", "BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT"),
	(0x2542, "╂", "lhhlNN", "BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT"),
	(0x2543, "╃", "hlhlNN", "BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT"),
	(0x2544, "╄", "llhhNN", "BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT"),
	(0x2545, "╅", "hhllNN", "BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT"),
	(0x2546, "╆", "lhlhNN", "BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT"),
	(0x2547, "╇", "hlhhNN", "BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY"),
	(0x2548, "╈", "hhlhNN", "BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY"),
	(0x2549, "╉", "hhhlNN", "BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY"),
	(0x254A, "╊", "lhhhNN", "BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY"),
	(0x254B, "╋", "hhhhNN", "BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL"),
# Light and heavy dashed lines
	(0x254C, "╌", "l--l2N", "BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL"),
	(0x254D, "╍", "h--h2N", "BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL"),
	(0x254E, "╎", "-ll-2N", "BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL"),
	(0x254F, "╏", "-hh-2N", "BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL"),
# Double lines
	(0x2550, "═", "d--dNN", "BOX DRAWINGS DOUBLE HORIZONTAL"),
	(0x2551, "║", "-dd-NN", "BOX DRAWINGS DOUBLE VERTICAL"),
# Light and double line box components
	(0x2552, "╒", "-l-dNN", "BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE"),
	(0x2553, "╓", "-d-lNN", "BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE"),
	(0x2554, "╔", "-d-dNN", "BOX DRAWINGS DOUBLE DOWN AND RIGHT"),
	(0x2555, "╕", "dl--NN", "BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE"),
	(0x2556, "╖", "ld--NN", "BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE"),
	(0x2557, "╗", "dd--NN", "BOX DRAWINGS DOUBLE DOWN AND LEFT"),
	(0x2558, "╘", "--ldNN", "BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE"),
	(0x2559, "╙", "--dlNN", "BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE"),
	(0x255A, "╚", "--ddNN", "BOX DRAWINGS DOUBLE UP AND RIGHT"),
	(0x255B, "╛", "d-l-NN", "BOX DRAWINGS UP SINGLE AND LEFT DOUBLE"),
	(0x255C, "╜", "l-d-NN", "BOX DRAWINGS UP DOUBLE AND LEFT SINGLE"),
	(0x255D, "╝", "d-d-NN", "BOX DRAWINGS DOUBLE UP AND LEFT"),
	(0x255E, "╞", "-lldNN", "BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE"),
	(0x255F, "╟", "-ddlNN", "BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE"),
	(0x2560, "╠", "-dddNN", "BOX DRAWINGS DOUBLE VERTICAL AND RIGHT"),
	(0x2561, "╡", "dll-NN", "BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE"),
	(0x2562, "╢", "ldd-NN", "BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE"),
	(0x2563, "╣", "ddd-NN", "BOX DRAWINGS DOUBLE VERTICAL AND LEFT"),
	(0x2564, "╤", "dl-dNN", "BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE"),
	(0x2565, "╥", "ld-lNN", "BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE"),
	(0x2566, "╦", "dd-dNN", "BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL"),
	(0x2567, "╧", "d-ldNN", "BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE"),
	(0x2568, "╨", "l-dlNN", "BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE"),
	(0x2569, "╩", "d-ddNN", "BOX DRAWINGS DOUBLE UP AND HORIZONTAL"),
	(0x256A, "╪", "dlldNN", "BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE"),
	(0x256B, "╫", "lddlNN", "BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE"),
	(0x256C, "╬", "ddddNN", "BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL"),
# Character cell arcs
	(0x256D, "╭", "-l-lNY", "BOX DRAWINGS LIGHT ARC DOWN AND RIGHT"),
	(0x256E, "╮", "ll--NY", "BOX DRAWINGS LIGHT ARC DOWN AND LEFT"),
	(0x256F, "╯", "l-l-NY", "BOX DRAWINGS LIGHT ARC UP AND LEFT"),
	(0x2570, "╰", "--llNY", "BOX DRAWINGS LIGHT ARC UP AND RIGHT"),
# Character cell diagonals
	(0x2571, "╱", None,     "BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT"),
	(0x2572, "╲", None,     "BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT"),
	(0x2573, "╳", None,     "BOX DRAWINGS LIGHT DIAGONAL CROSS"),
# Light and heavy half lines
	(0x2574, "╴", "l---NN", "BOX DRAWINGS LIGHT LEFT"),
	(0x2575, "╵", "--l-NN", "BOX DRAWINGS LIGHT UP"),
	(0x2576, "╶", "---lNN", "BOX DRAWINGS LIGHT RIGHT"),
	(0x2577, "╷", "-l--NN", "BOX DRAWINGS LIGHT DOWN"),
	(0x2578, "╸", "h---NN", "BOX DRAWINGS HEAVY LEFT"),
	(0x2579, "╹", "--h-NN", "BOX DRAWINGS HEAVY UP"),
	(0x257A, "╺", "---hNN", "BOX DRAWINGS HEAVY RIGHT"),
	(0x257B, "╻", "-h--NN", "BOX DRAWINGS HEAVY DOWN"),
# Mixed light and heavy lines
	(0x257C, "╼", "l--hNN", "BOX DRAWINGS LIGHT LEFT AND HEAVY RIGHT"),
	(0x257D, "╽", "-hl-NN", "BOX DRAWINGS LIGHT UP AND HEAVY DOWN"),
	(0x257E, "╾", "h--lNN", "BOX DRAWINGS HEAVY LEFT AND LIGHT RIGHT"),
	(0x257F, "╿", "-lh-NN", "BOX DRAWINGS HEAVY UP AND LIGHT DOWN")]

boxdict={}
for (code, char, prop, desc) in boxlist:
	d={"code":code, "char":char, "prop": prop, "desc":desc}
	boxdict[code]=d
	boxdict[char]=d
	if(prop):
		boxdict[prop]=d
	boxdict[desc]=d

def boxdrawings_bestmatch(prop):
	ldur=prop[:4]
	if(len(ldur.split("h"))>len(ldur.split("d"))):
		ldur_=ldur.replace("d", "h")
	else:
		ldur_=ldur.replace("h", "d")
	d=prop[4]
	a=prop[5]
	candidates=[
		ldur + d + a ,
		ldur + d +"N",
		ldur +"N"+ a ,
		ldur +"N"+"N",
		ldur_+ d + a ,
		ldur_+ d +"N",
		ldur_+"N"+ a ,
		ldur_+"N"+"N"]
	for candidate in candidates:
		if(candidate in boxdict):
			return boxdict[candidate]
	return None
