#!/bin/bash

die() { echo Error: "$@">&2;exit 1; }

[ "$OSTYPE" = cygwin ] || die Building only supported under Cygwin.
which i686-w64-mingw32-gcc>/dev/null || die mingw32 compiler not found. Install cygwin package mingw64-i686-gcc-core.

i686-w64-mingw32-gcc -o listenkey.exe listenkey.c || die Compilation failed
i686-w64-mingw32-gcc -o sendkey.exe sendkey.c || die Compilation failed

echo Success!
