#!/usr/bin/env bash

# Print a string identifying the current version of the code.
# This is used in the build process.

# projectversion=`git describe --tags --long`
# cleanversion=${projectversion%%-*}

if which git >/dev/null 2>&1; then :; else
	echo UNKNOWN
	exit 1
fi

revisioncount=`git log --oneline | wc -l`
ts=`date +%Y%m%d.%H%M%S`
id=`git rev-parse --short HEAD`
tag=`git tag --points-at HEAD`

if git diff --quiet --exit-code HEAD; then
	if [ -z "$tag" ]; then
		# clean working dir but untagged commit
		echo snapshot-$id-$revisioncount
	else
		# clean working dir on tagged commit
		echo $tag
	fi
else
	# dirty working dir
	echo dev-$ts
fi
