#!/usr/bin/env bash

# A script that prints a string identifying the current version of the code
# This is used in the build process as a fallback

# projectversion=`git describe --tags --long`
# cleanversion=${projectversion%%-*}

revisioncount=`git log --oneline | wc -l`
ts=`date +%Y%m%d.%H%M%S`
id=`git rev-parse --short HEAD`

if git diff --quiet --exit-code HEAD; then
	echo $id-$revisioncount-snapshot
else
	echo $ts-dev
fi
